==9396== Memcheck, a memory error detector
==9396== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==9396== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==9396== Command: python smalltest.py
==9396== Parent PID: 7626
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4E9C04A: code_dealloc (codeobject.c:347)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E983: import_module_level (import.c:2247)
==9396==    by 0x4F4E983: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==  Address 0x6026020 is 592 bytes inside a block of size 848 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EBAD40: list_resize (listobject.c:62)
==9396==    by 0x4EBAD40: app1 (listobject.c:277)
==9396==    by 0x4EBAD40: PyList_Append (listobject.c:289)
==9396==    by 0x4F51473: r_object (marshal.c:828)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BFF: r_object (marshal.c:1027)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==  Address 0x611a020 is 32 bytes before a block of size 560 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4E9C025: code_dealloc (codeobject.c:357)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==9396==    by 0x4F4EAF3: import_module_level (import.c:2293)
==9396==    by 0x4F4EAF3: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==  Address 0x7287020 is 224 bytes inside a block of size 256 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EE0339: string_subscript (stringobject.c:1335)
==9396==    by 0x4F309E6: PyEval_EvalFrameEx (ceval.c:1539)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EE5202: tupledealloc (tupleobject.c:235)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==9396==    by 0x4F4EAF3: import_module_level (import.c:2293)
==9396==    by 0x4F4EAF3: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==  Address 0x7440020 is 448 bytes inside a block of size 1,184 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EBAD40: list_resize (listobject.c:62)
==9396==    by 0x4EBAD40: app1 (listobject.c:277)
==9396==    by 0x4EBAD40: PyList_Append (listobject.c:289)
==9396==    by 0x4F51473: r_object (marshal.c:828)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50C13: r_object (marshal.c:1030)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EE5202: tupledealloc (tupleobject.c:235)
==9396==    by 0x4E9C0BA: code_dealloc (codeobject.c:349)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==9396==    by 0x4F4EAF3: import_module_level (import.c:2293)
==9396==    by 0x4F4EAF3: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==  Address 0x7442020 is 304 bytes inside a block of size 1,384 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EBAD40: list_resize (listobject.c:62)
==9396==    by 0x4EBAD40: app1 (listobject.c:277)
==9396==    by 0x4EBAD40: PyList_Append (listobject.c:289)
==9396==    by 0x4F51473: r_object (marshal.c:828)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BFF: r_object (marshal.c:1027)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4E7BB29: PyNode_AddChild (node.c:98)
==9396==    by 0x4E7CC9C: shift (parser.c:112)
==9396==    by 0x4E7CC9C: PyParser_AddToken (parser.c:262)
==9396==    by 0x4E7CF43: parsetok (parsetok.c:198)
==9396==    by 0x4F57782: PyParser_ASTFromString (pythonrun.c:1470)
==9396==    by 0x4F57977: PyRun_StringFlags (pythonrun.c:1337)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==  Address 0x74f1020 is 16 bytes after a block of size 992 alloc'd
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4E80D5D: tok_new (tokenizer.c:100)
==9396==    by 0x4E80D5D: PyTokenizer_FromString (tokenizer.c:736)
==9396==    by 0x4E7D43F: PyParser_ParseStringFlagsFilenameEx (parsetok.c:54)
==9396==    by 0x4F57782: PyParser_ASTFromString (pythonrun.c:1470)
==9396==    by 0x4F57977: PyRun_StringFlags (pythonrun.c:1337)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3BD61: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3BD61: compiler_nameop (compile.c:2434)
==9396==    by 0x4F3EE34: compiler_visit_stmt (compile.c:2105)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==  Address 0xd593020 is 576 bytes inside a block of size 768 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED1D54: PyObject_Realloc (obmalloc.c:1272)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3AC5C: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3AC5C: compiler_addop_o (compile.c:980)
==9396==    by 0x4F3C840: compiler_visit_expr (compile.c:3031)
==9396==    by 0x4F3D013: compiler_visit_expr (compile.c:2972)
==9396==    by 0x4F3C967: compiler_call (compile.c:2544)
==9396==    by 0x4F3C967: compiler_visit_expr (compile.c:3022)
==9396==    by 0x4F3EA95: compiler_visit_stmt (compile.c:2122)
==9396==    by 0x4F40A57: compiler_if (compile.c:1595)
==9396==    by 0x4F3FFDD: compiler_function (compile.c:1379)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4EDFC28: output_extend (string_format.h:162)
==9396==    by 0x4EDFC28: output_data (string_format.h:184)
==9396==    by 0x4EDFC28: render_field (string_format.h:626)
==9396==    by 0x4EDFC28: output_markup (string_format.h:926)
==9396==    by 0x4EDFC28: do_markup (string_format.h:965)
==9396==    by 0x4EDFC28: build_string (string_format.h:1002)
==9396==    by 0x4EDFF8B: do_string_format (string_format.h:1041)
==9396==    by 0x4F37FA3: do_call (ceval.c:4566)
==9396==    by 0x4F37FA3: call_function (ceval.c:4374)
==9396==    by 0x4F37FA3: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==  Address 0xd5de020 is 2,768 bytes inside a block of size 4,097 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F4E7DC: import_module_level (import.c:2238)
==9396==    by 0x4F4E7DC: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E384: load_next (import.c:2543)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4EDF84F: build_string (string_format.h:1008)
==9396==    by 0x4EDFF8B: do_string_format (string_format.h:1041)
==9396==    by 0x4F37FA3: do_call (ceval.c:4566)
==9396==    by 0x4F37FA3: call_function (ceval.c:4374)
==9396==    by 0x4F37FA3: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==  Address 0xd5df020 is 704 bytes inside a block of size 1,559 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED9A79: PyString_FromStringAndSize (stringobject.c:88)
==9396==    by 0x4EDF456: output_initialize (string_format.h:138)
==9396==    by 0x4EDF456: build_string (string_format.h:997)
==9396==    by 0x4EDFF8B: do_string_format (string_format.h:1041)
==9396==    by 0x4F37FA3: do_call (ceval.c:4566)
==9396==    by 0x4F37FA3: call_function (ceval.c:4374)
==9396==    by 0x4F37FA3: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3C2F1: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3C2F1: compiler_make_closure (compile.c:1265)
==9396==    by 0x4F4003D: compiler_function (compile.c:1386)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==  Address 0xd5f1020 is 80 bytes inside a block of size 768 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EC754F: dictresize (dictobject.c:643)
==9396==    by 0x4F5C443: analyze_name (symtable.c:398)
==9396==    by 0x4F5C443: analyze_block (symtable.c:669)
==9396==    by 0x4F5C631: analyze_child_block (symtable.c:762)
==9396==    by 0x4F5C631: analyze_block (symtable.c:701)
==9396==    by 0x4F5E63B: symtable_analyze (symtable.c:791)
==9396==    by 0x4F5E63B: PySymtable_Build (symtable.c:266)
==9396==    by 0x4F4244C: PyAST_Compile (compile.c:285)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4DB79: load_package (import.c:1188)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==  Address 0xf073020 is 2,528 bytes inside a block of size 2,572 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F51818: PyMarshal_ReadLastObjectFromFile (marshal.c:1146)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4DB79: load_package (import.c:1188)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==9396==    by 0x4F4EAF3: import_module_level (import.c:2293)
==9396==    by 0x4F4EAF3: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==  Address 0x7157020 is 16 bytes after a block of size 864 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4EDE40E: PyString_FromFormatV (stringobject.c:394)
==9396==    by 0x4EDEA2C: PyString_FromFormat (stringobject.c:410)
==9396==    by 0xC33ABFC: ufunc_get_doc (ufunc_object.c:5629)
==9396==    by 0x4ECF37A: _PyObject_GenericGetAttrWithDict (object.c:1439)
==9396==    by 0x4F2C5D0: builtin_getattr (bltinmodule.c:848)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==  Address 0xff5f020 is 2,048 bytes inside a block of size 4,097 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F4E7DC: import_module_level (import.c:2238)
==9396==    by 0x4F4E7DC: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E8715B: call_function_tail (abstract.c:2579)
==9396==    by 0x4E8715B: PyObject_CallFunction (abstract.c:2603)
==9396==    by 0x4F4EFBC: PyImport_Import (import.c:2911)
==9396==    by 0x4F4F16B: PyImport_ImportModule (import.c:2151)
==9396==    by 0xC33AC2B: npy_cache_import (npy_import.h:23)
==9396==    by 0xC33AC2B: ufunc_get_doc (ufunc_object.c:5609)
==9396==    by 0x4ECF37A: _PyObject_GenericGetAttrWithDict (object.c:1439)
==9396==    by 0x4F2C5D0: builtin_getattr (bltinmodule.c:848)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4EE1392: PyString_Format (stringobject.c:4687)
==9396==    by 0x4F363BA: PyEval_EvalFrameEx (ceval.c:1450)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==  Address 0x1051c020 is 0 bytes inside a block of size 32 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EBC530: list_resize (listobject.c:62)
==9396==    by 0x4EBC530: listextend (listobject.c:827)
==9396==    by 0x4E887C1: PySequence_List (abstract.c:2265)
==9396==    by 0x4EEF461: mro_implementation (typeobject.c:1616)
==9396==    by 0x4EECA1A: mro_internal (typeobject.c:1660)
==9396==    by 0x4EED007: PyType_Ready (typeobject.c:4154)
==9396==    by 0x4EF5327: type_new (typeobject.c:2512)
==9396==    by 0x4EE7522: type_call (typeobject.c:749)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E88A65: PyObject_CallFunctionObjArgs (abstract.c:2774)
==9396==    by 0x4F321EB: build_class (ceval.c:4964)
==9396==    by 0x4F321EB: PyEval_EvalFrameEx (ceval.c:2160)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3C285: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3C285: compiler_addop_o (compile.c:980)
==9396==    by 0x4F3C285: compiler_make_closure (compile.c:1264)
==9396==    by 0x4F4003D: compiler_function (compile.c:1386)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==  Address 0x10752020 is 96 bytes inside a block of size 768 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EC754F: dictresize (dictobject.c:643)
==9396==    by 0x4F5C415: analyze_name (symtable.c:397)
==9396==    by 0x4F5C415: analyze_block (symtable.c:669)
==9396==    by 0x4F5C631: analyze_child_block (symtable.c:762)
==9396==    by 0x4F5C631: analyze_block (symtable.c:701)
==9396==    by 0x4F5C631: analyze_child_block (symtable.c:762)
==9396==    by 0x4F5C631: analyze_block (symtable.c:701)
==9396==    by 0x4F5E63B: symtable_analyze (symtable.c:791)
==9396==    by 0x4F5E63B: PySymtable_Build (symtable.c:266)
==9396==    by 0x4F4244C: PyAST_Compile (compile.c:285)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F39637: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3D3A8: compiler_tuple (compile.c:2487)
==9396==    by 0x4F3D3A8: compiler_visit_expr (compile.c:3094)
==9396==    by 0x4F3EDB3: compiler_visit_stmt (compile.c:2101)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==  Address 0x10754020 is 16 bytes inside a block of size 32 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EB8F38: list_resize (listobject.c:62)
==9396==    by 0x4EBBA52: list_ass_slice (listobject.c:687)
==9396==    by 0x4F39CF9: compiler_exit_scope (compile.c:552)
==9396==    by 0x4F40017: compiler_function (compile.c:1382)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4EDF61D: output_extend (string_format.h:162)
==9396==    by 0x4EDF61D: output_data (string_format.h:184)
==9396==    by 0x4EDF61D: do_markup (string_format.h:962)
==9396==    by 0x4EDF61D: build_string (string_format.h:1002)
==9396==    by 0x4EDFF8B: do_string_format (string_format.h:1041)
==9396==    by 0x4F37FA3: do_call (ceval.c:4566)
==9396==    by 0x4F37FA3: call_function (ceval.c:4374)
==9396==    by 0x4F37FA3: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==  Address 0x10759020 is 16 bytes after a block of size 64 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3BD61: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3BD61: compiler_nameop (compile.c:2434)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==  Address 0x107d8020 is 32 bytes inside a block of size 768 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EC754F: dictresize (dictobject.c:643)
==9396==    by 0x4F3C506: list2dict (compile.c:342)
==9396==    by 0x4F3C506: compiler_enter_scope (compile.c:484)
==9396==    by 0x4F3FE94: compiler_function (compile.c:1358)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3AC5C: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3AC5C: compiler_addop_o (compile.c:980)
==9396==    by 0x4F3C840: compiler_visit_expr (compile.c:3031)
==9396==    by 0x4F3CA37: compiler_visit_keyword (compile.c:2847)
==9396==    by 0x4F3CA37: compiler_call (compile.c:2546)
==9396==    by 0x4F3CA37: compiler_visit_expr (compile.c:3022)
==9396==    by 0x4F3EDB3: compiler_visit_stmt (compile.c:2101)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==  Address 0x107da020 is 272 bytes inside a block of size 768 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED1D54: PyObject_Realloc (obmalloc.c:1272)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F409D7: compiler_addop_j (compile.c:1025)
==9396==    by 0x4F409D7: compiler_if (compile.c:1594)
==9396==    by 0x4F3FFDD: compiler_function (compile.c:1379)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3C9CA: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3C9CA: compiler_addop_o (compile.c:980)
==9396==    by 0x4F3C9CA: compiler_visit_keyword (compile.c:2846)
==9396==    by 0x4F3C9CA: compiler_call (compile.c:2546)
==9396==    by 0x4F3C9CA: compiler_visit_expr (compile.c:3022)
==9396==    by 0x4F3EDB3: compiler_visit_stmt (compile.c:2101)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==  Address 0x11233020 is 64 bytes inside a block of size 88 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F54D82: PyCode_Optimize (peephole.c:346)
==9396==    by 0x4F3BA35: makecode (compile.c:3844)
==9396==    by 0x4F3BA35: assemble (compile.c:3960)
==9396==    by 0x4F4000C: compiler_function (compile.c:1381)
==9396==    by 0x4F3FC2D: compiler_body (compile.c:1168)
==9396==    by 0x4F3FC2D: compiler_class (compile.c:1435)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F57993: run_mod (pythonrun.c:1373)
==9396==    by 0x4F57993: PyRun_StringFlags (pythonrun.c:1339)
==9396==    by 0x4F35661: exec_statement (ceval.c:5086)
==9396==    by 0x4F35661: PyEval_EvalFrameEx (ceval.c:2106)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F02E6A: PyUnicodeUCS4_DecodeUTF8Stateful (unicodeobject.c:2131)
==9396==    by 0x4F51212: r_object (marshal.c:871)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396==  Address 0x5f82020 is 384 bytes inside a block of size 768 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EC754F: dictresize (dictobject.c:643)
==9396==    by 0x4F4AABC: _PyImport_AddModuleObject (import.c:652)
==9396==    by 0x4F4AABC: PyImport_AddModule (import.c:669)
==9396==    by 0x4F5338F: Py_InitModule4_64 (modsupport.c:65)
==9396==    by 0x4F116CF: _PyWarnings_Init (_warnings.c:886)
==9396==    by 0x4F59FA7: Py_InitializeEx (pythonrun.c:268)
==9396==    by 0x4F6E7D5: Py_Main (main.c:547)
==9396==    by 0x5B843F0: (below main) (libc-start.c:291)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EF9F68: unicode_dealloc (unicodeobject.c:394)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==  Address 0x5f40020 is 0 bytes after a block of size 304 alloc'd
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F02E6A: PyUnicodeUCS4_DecodeUTF8Stateful (unicodeobject.c:2131)
==9396==    by 0x4F51212: r_object (marshal.c:871)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F06D82: PyUnicodeUCS4_Join (unicodeobject.c:5750)
==9396==    by 0x4F37D3C: call_function (ceval.c:4340)
==9396==    by 0x4F37D3C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==  Address 0x5fd8020 is 96 bytes inside a block of size 720 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E983: import_module_level (import.c:2247)
==9396==    by 0x4F4E983: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F06E00: PyUnicodeUCS4_Join (unicodeobject.c:5771)
==9396==    by 0x4F37D3C: call_function (ceval.c:4340)
==9396==    by 0x4F37D3C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==  Address 0x5fa6020 is 1,728 bytes inside a block of size 4,097 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F4E7DC: import_module_level (import.c:2238)
==9396==    by 0x4F4E7DC: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F0B143: PyUnicodeUCS4_Format (unicodeobject.c:8738)
==9396==    by 0x4E84A31: binary_op1 (abstract.c:945)
==9396==    by 0x4E87DED: binary_op (abstract.c:997)
==9396==    by 0x4E87DED: PyNumber_Remainder (abstract.c:1249)
==9396==    by 0x4F3151E: PyEval_EvalFrameEx (ceval.c:1452)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==  Address 0x6075020 is 3,440 bytes inside an unallocated block of size 4,112 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F0ACF4: PyUnicodeUCS4_Format (unicodeobject.c:8803)
==9396==    by 0x4E84A31: binary_op1 (abstract.c:945)
==9396==    by 0x4E87DED: binary_op (abstract.c:997)
==9396==    by 0x4E87DED: PyNumber_Remainder (abstract.c:1249)
==9396==    by 0x4F3151E: PyEval_EvalFrameEx (ceval.c:1452)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==  Address 0x6065020 is 2,224 bytes inside a block of size 4,212 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F0B143: PyUnicodeUCS4_Format (unicodeobject.c:8738)
==9396==    by 0x4E84A31: binary_op1 (abstract.c:945)
==9396==    by 0x4E87DED: binary_op (abstract.c:997)
==9396==    by 0x4E87DED: PyNumber_Remainder (abstract.c:1249)
==9396==    by 0x4F3151E: PyEval_EvalFrameEx (ceval.c:1452)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4F2EDA4: string_concatenate (ceval.c:5172)
==9396==    by 0x4F36859: PyEval_EvalFrameEx (ceval.c:1478)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==  Address 0x60f4020 is 4,384 bytes inside a block of size 5,174 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED9A79: PyString_FromStringAndSize (stringobject.c:88)
==9396==    by 0x4EDB896: string_join (stringobject.c:1659)
==9396==    by 0x4F37D3C: call_function (ceval.c:4340)
==9396==    by 0x4F37D3C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EE5202: tupledealloc (tupleobject.c:235)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==  Address 0x60fa020 is 19 bytes after a block of size 733 alloc'd
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED9A79: PyString_FromStringAndSize (stringobject.c:88)
==9396==    by 0x4F502F9: r_object (marshal.c:814)
==9396==    by 0x4F50BD5: r_object (marshal.c:1021)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396==  Address 0x11362020 is 32 bytes before a block of size 48 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4E9C05A: code_dealloc (codeobject.c:355)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4F4D33C: load_source_module (import.c:1122)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396==    by 0x4F4E9D7: import_module_level (import.c:2256)
==9396==    by 0x4F4E9D7: PyImport_ImportModuleLevel (import.c:2312)
==9396==    by 0x4F2E2CE: builtin___import__ (bltinmodule.c:49)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F33445: PyEval_EvalFrameEx (ceval.c:2624)
==9396==  Address 0x6199020 is 288 bytes inside a block of size 752 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EE541E: PyTuple_New (tupleobject.c:90)
==9396==    by 0x4F50A3D: r_object (marshal.c:885)
==9396==    by 0x4F50BFF: r_object (marshal.c:1027)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F0ACF4: PyUnicodeUCS4_Format (unicodeobject.c:8803)
==9396==    by 0x4EE1A50: PyString_Format (stringobject.c:4725)
==9396==    by 0x4F363BA: PyEval_EvalFrameEx (ceval.c:1450)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==  Address 0x6216020 is 208 bytes inside an unallocated block of size 432 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F06E00: PyUnicodeUCS4_Join (unicodeobject.c:5771)
==9396==    by 0x4EDB77F: string_join (stringobject.c:1635)
==9396==    by 0x4F37D3C: call_function (ceval.c:4340)
==9396==    by 0x4F37D3C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==  Address 0x62f5020 is 32 bytes before a block of size 16 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4EFD183: unicodeescape_string (unicodeobject.c:3183)
==9396==    by 0x4ED0944: PyObject_Repr (object.c:381)
==9396==    by 0x4F37D3C: call_function (ceval.c:4340)
==9396==    by 0x4F37D3C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==  Address 0xfc5b020 is 96 bytes inside a block of size 1,104 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F7D35E: data_stack_grow (_sre.c:276)
==9396==    by 0x4F7D35E: sre_match (_sre.c:825)
==9396==    by 0x4F83375: pattern_match (_sre.c:1956)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F00BAE: unicode_resize (unicodeobject.c:288)
==9396==    by 0x4F00BAE: _PyUnicode_Resize (unicodeobject.c:445)
==9396==    by 0x4F06D82: PyUnicodeUCS4_Join (unicodeobject.c:5750)
==9396==    by 0x4EDB77F: string_join (stringobject.c:1635)
==9396==    by 0x4F37D3C: call_function (ceval.c:4340)
==9396==    by 0x4F37D3C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==  Address 0xfd49020 is 32 bytes before a block of size 560 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4EFD593: PyUnicodeUCS4_EncodeUTF8 (unicodeobject.c:2238)
==9396==    by 0x4F2DEE0: builtin_compile (bltinmodule.c:547)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==  Address 0xfca1020 is 336 bytes inside a block of size 1,104 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F7D35E: data_stack_grow (_sre.c:276)
==9396==    by 0x4F7D35E: sre_match (_sre.c:825)
==9396==    by 0x4F7F2B2: sre_search (_sre.c:1631)
==9396==    by 0x4F82704: pattern_subx (_sre.c:2442)
==9396==    by 0x4F82D00: pattern_sub (_sre.c:2564)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4E7BB29: PyNode_AddChild (node.c:98)
==9396==    by 0x4E7CA66: push (parser.c:126)
==9396==    by 0x4E7CA66: PyParser_AddToken (parser.c:252)
==9396==    by 0x4E7CF43: parsetok (parsetok.c:198)
==9396==    by 0x4F57705: PyParser_ASTFromString (pythonrun.c:1470)
==9396==    by 0x4F5788B: Py_CompileStringFlags (pythonrun.c:1423)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==  Address 0xf1b7020 is 800 bytes inside a block of size 1,104 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F7F9DE: data_stack_grow (_sre.c:276)
==9396==    by 0x4F7F9DE: sre_umatch (_sre.c:825)
==9396==    by 0x4F8333D: pattern_match (_sre.c:1959)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3BF2C: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3BF2C: compiler_addop_o (compile.c:980)
==9396==    by 0x4F3BF2C: compiler_nameop (compile.c:2394)
==9396==    by 0x4F3EE34: compiler_visit_stmt (compile.c:2105)
==9396==    by 0x4F40DEF: compiler_try_finally (compile.c:1768)
==9396==    by 0x4F3FFDD: compiler_function (compile.c:1379)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F578AE: Py_CompileStringFlags (pythonrun.c:1433)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==  Address 0xfe0b020 is 1,072 bytes inside a block of size 3,072 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EC754F: dictresize (dictobject.c:643)
==9396==    by 0x4F5C443: analyze_name (symtable.c:398)
==9396==    by 0x4F5C443: analyze_block (symtable.c:669)
==9396==    by 0x4F5C631: analyze_child_block (symtable.c:762)
==9396==    by 0x4F5C631: analyze_block (symtable.c:701)
==9396==    by 0x4F5E63B: symtable_analyze (symtable.c:791)
==9396==    by 0x4F5E63B: PySymtable_Build (symtable.c:266)
==9396==    by 0x4F4244C: PyAST_Compile (compile.c:285)
==9396==    by 0x4F578AE: Py_CompileStringFlags (pythonrun.c:1433)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F3BF2C: compiler_addop_i (compile.c:1007)
==9396==    by 0x4F3BF2C: compiler_addop_o (compile.c:980)
==9396==    by 0x4F3BF2C: compiler_nameop (compile.c:2394)
==9396==    by 0x4F3C93B: compiler_call (compile.c:2542)
==9396==    by 0x4F3C93B: compiler_visit_expr (compile.c:3022)
==9396==    by 0x4F3E28E: compiler_visit_stmt (compile.c:2169)
==9396==    by 0x4F40A57: compiler_if (compile.c:1595)
==9396==    by 0x4F403C3: compiler_for (compile.c:1624)
==9396==    by 0x4F40DEF: compiler_try_finally (compile.c:1768)
==9396==    by 0x4F3FFDD: compiler_function (compile.c:1379)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F578AE: Py_CompileStringFlags (pythonrun.c:1433)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==  Address 0xfc7d020 is 2,112 bytes inside a block of size 6,072 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EFA9EC: _PyUnicode_New (unicodeobject.c:348)
==9396==    by 0x4F01858: PyUnicodeUCS4_DecodeASCII (unicodeobject.c:3843)
==9396==    by 0x4F034C5: PyUnicodeUCS4_FromEncodedObject (unicodeobject.c:1228)
==9396==    by 0x4F06D12: PyUnicodeUCS4_Join (unicodeobject.c:5725)
==9396==    by 0x4EDB77F: string_join (stringobject.c:1635)
==9396==    by 0x4F37D3C: call_function (ceval.c:4340)
==9396==    by 0x4F37D3C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F396EF: compiler_addop_j (compile.c:1025)
==9396==    by 0x4F40A7A: compiler_if (compile.c:1596)
==9396==    by 0x4F403C3: compiler_for (compile.c:1624)
==9396==    by 0x4F40DEF: compiler_try_finally (compile.c:1768)
==9396==    by 0x4F3FFDD: compiler_function (compile.c:1379)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F578AE: Py_CompileStringFlags (pythonrun.c:1433)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==  Address 0xd7b6020 is 224 bytes inside a block of size 1,104 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F7F9DE: data_stack_grow (_sre.c:276)
==9396==    by 0x4F7F9DE: sre_umatch (_sre.c:825)
==9396==    by 0x4F81B6F: sre_usearch (_sre.c:1631)
==9396==    by 0x4F82514: pattern_subx (_sre.c:2445)
==9396==    by 0x4F82D00: pattern_sub (_sre.c:2564)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4F39598: compiler_next_instr (compile.c:650)
==9396==    by 0x4F397A7: compiler_addop (compile.c:929)
==9396==    by 0x4F3E3E7: compiler_from_import (compile.c:2032)
==9396==    by 0x4F3E3E7: compiler_visit_stmt (compile.c:2144)
==9396==    by 0x4F40A57: compiler_if (compile.c:1595)
==9396==    by 0x4F403C3: compiler_for (compile.c:1624)
==9396==    by 0x4F40DEF: compiler_try_finally (compile.c:1768)
==9396==    by 0x4F3FFDD: compiler_function (compile.c:1379)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F578AE: Py_CompileStringFlags (pythonrun.c:1433)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==  Address 0xfd08020 is 960 bytes inside a block of size 1,104 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F7F9DE: data_stack_grow (_sre.c:276)
==9396==    by 0x4F7F9DE: sre_umatch (_sre.c:825)
==9396==    by 0x4F8333D: pattern_match (_sre.c:1959)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4F3B19F: assemble_emit (compile.c:3664)
==9396==    by 0x4F3B19F: assemble (compile.c:3951)
==9396==    by 0x4F4000C: compiler_function (compile.c:1381)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F578AE: Py_CompileStringFlags (pythonrun.c:1433)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==  Address 0xd595020 is 144 bytes inside a block of size 1,760 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4E7BB29: PyNode_AddChild (node.c:98)
==9396==    by 0x4E7CA66: push (parser.c:126)
==9396==    by 0x4E7CA66: PyParser_AddToken (parser.c:252)
==9396==    by 0x4E7CF43: parsetok (parsetok.c:198)
==9396==    by 0x4F57705: PyParser_ASTFromString (pythonrun.c:1470)
==9396==    by 0x4F5788B: Py_CompileStringFlags (pythonrun.c:1423)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED1C9E: PyObject_Realloc (obmalloc.c:1253)
==9396==    by 0x4EDBBB6: _PyString_Resize (stringobject.c:3909)
==9396==    by 0x4F3B230: assemble (compile.c:3955)
==9396==    by 0x4F4000C: compiler_function (compile.c:1381)
==9396==    by 0x4F424ED: compiler_body (compile.c:1168)
==9396==    by 0x4F424ED: compiler_mod (compile.c:1188)
==9396==    by 0x4F424ED: PyAST_Compile (compile.c:292)
==9396==    by 0x4F578AE: Py_CompileStringFlags (pythonrun.c:1433)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==  Address 0xfd0c020 is 144 bytes inside a block of size 1,104 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F7F9DE: data_stack_grow (_sre.c:276)
==9396==    by 0x4F7F9DE: sre_umatch (_sre.c:825)
==9396==    by 0x4F8333D: pattern_match (_sre.c:1959)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Warning: noted but unhandled ioctl 0x30000001 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: noted but unhandled ioctl 0x27 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: noted but unhandled ioctl 0x7ff with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: noted but unhandled ioctl 0x25 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: noted but unhandled ioctl 0x37 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: noted but unhandled ioctl 0x17 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: set address range perms: large range [0x200000000, 0x300200000) (noaccess)
==9396== Warning: set address range perms: large range [0x10006000000, 0x10106000000) (noaccess)
==9396== Warning: noted but unhandled ioctl 0x19 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: set address range perms: large range [0x10106000000, 0x10206000000) (noaccess)
==9396== Warning: noted but unhandled ioctl 0x21 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: noted but unhandled ioctl 0x1b with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EF9F68: unicode_dealloc (unicodeobject.c:394)
==9396==    by 0x4EC940A: dict_dealloc (dictobject.c:1040)
==9396==    by 0x4EE8D00: subtype_dealloc (typeobject.c:1035)
==9396==    by 0x4EB971E: list_dealloc (listobject.c:309)
==9396==    by 0x4EC940A: dict_dealloc (dictobject.c:1040)
==9396==    by 0x4EE8D00: subtype_dealloc (typeobject.c:1035)
==9396==    by 0x4EC940A: dict_dealloc (dictobject.c:1040)
==9396==    by 0x4EE8D00: subtype_dealloc (typeobject.c:1035)
==9396==    by 0x4EB971E: list_dealloc (listobject.c:309)
==9396==    by 0x4EC940A: dict_dealloc (dictobject.c:1040)
==9396==    by 0x4EE9145: subtype_clear (typeobject.c:912)
==9396==  Address 0x601e020 is 9,632 bytes inside a block of size 10,016 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4EFA9EC: _PyUnicode_New (unicodeobject.c:348)
==9396==    by 0x4F02A26: PyUnicodeUCS4_DecodeUTF8Stateful (unicodeobject.c:1985)
==9396==    by 0x4F847A8: utf_8_decode (_codecsmodule.c:270)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F2E7B2: PyEval_CallObjectWithKeywords (ceval.c:4221)
==9396==    by 0x4F4418C: _PyCodec_DecodeInternal (codecs.c:399)
==9396==    by 0x4EDDF00: string_decode (stringobject.c:3055)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Warning: noted but unhandled ioctl 0x42 with no size/direction hints.
==9396==    This could cause spurious value errors to appear.
==9396==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
==9396== Warning: set address range perms: large range [0x10106000000, 0x10206000000) (noaccess)
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4E9C04A: code_dealloc (codeobject.c:347)
==9396==    by 0x4EB3D0A: func_dealloc (funcobject.c:451)
==9396==    by 0x4EC940A: dict_dealloc (dictobject.c:1040)
==9396==    by 0x4E9566A: class_dealloc (classobject.c:195)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9567A: class_dealloc (classobject.c:194)
==9396==    by 0x4EC72C6: insertdict_by_entry (dictobject.c:519)
==9396==    by 0x4ECA79B: insertdict (dictobject.c:556)
==9396==    by 0x4ECA79B: dict_set_item_by_hash_or_entry (dictobject.c:795)
==9396==    by 0x4ECA79B: PyDict_SetItem (dictobject.c:848)
==9396==    by 0x4ECDA8C: _PyModule_Clear (moduleobject.c:139)
==9396==    by 0x4F4B4A0: PyImport_Cleanup (import.c:512)
==9396==    by 0x4F5857A: Py_Finalize (pythonrun.c:458)
==9396==  Address 0x10800020 is 1,184 bytes inside an unallocated block of size 4,256 in arena "client"
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EE5202: tupledealloc (tupleobject.c:235)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4EB3D0A: func_dealloc (funcobject.c:451)
==9396==    by 0x4EC940A: dict_dealloc (dictobject.c:1040)
==9396==    by 0x4EE8D00: subtype_dealloc (typeobject.c:1035)
==9396==    by 0x4EC72C6: insertdict_by_entry (dictobject.c:519)
==9396==    by 0x4ECA79B: insertdict (dictobject.c:556)
==9396==    by 0x4ECA79B: dict_set_item_by_hash_or_entry (dictobject.c:795)
==9396==    by 0x4ECA79B: PyDict_SetItem (dictobject.c:848)
==9396==    by 0x4ECDA8C: _PyModule_Clear (moduleobject.c:139)
==9396==    by 0x4F4B4A0: PyImport_Cleanup (import.c:512)
==9396==    by 0x4F5857A: Py_Finalize (pythonrun.c:458)
==9396==    by 0x4F6E8E4: Py_Main (main.c:670)
==9396==  Address 0xd717020 is 1,616 bytes inside a block of size 2,080 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4E7BB29: PyNode_AddChild (node.c:98)
==9396==    by 0x4E7CA66: push (parser.c:126)
==9396==    by 0x4E7CA66: PyParser_AddToken (parser.c:252)
==9396==    by 0x4E7CF43: parsetok (parsetok.c:198)
==9396==    by 0x4F57705: PyParser_ASTFromString (pythonrun.c:1470)
==9396==    by 0x4F5788B: Py_CompileStringFlags (pythonrun.c:1423)
==9396==    by 0x4F2DEA3: builtin_compile (bltinmodule.c:570)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9C0CA: code_dealloc (codeobject.c:348)
==9396==    by 0x4EB3D0A: func_dealloc (funcobject.c:451)
==9396==    by 0x4EC72C6: insertdict_by_entry (dictobject.c:519)
==9396==    by 0x4ECA79B: insertdict (dictobject.c:556)
==9396==    by 0x4ECA79B: dict_set_item_by_hash_or_entry (dictobject.c:795)
==9396==    by 0x4ECA79B: PyDict_SetItem (dictobject.c:848)
==9396==    by 0x4ECD9C9: _PyModule_Clear (moduleobject.c:125)
==9396==    by 0x4F4B4A0: PyImport_Cleanup (import.c:512)
==9396==    by 0x4F5857A: Py_Finalize (pythonrun.c:458)
==9396==    by 0x4F6E8E4: Py_Main (main.c:670)
==9396==  Address 0xd5d7020 is 736 bytes inside a block of size 1,104 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DA5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4C2FDDF: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F7F9DE: data_stack_grow (_sre.c:276)
==9396==    by 0x4F7F9DE: sre_umatch (_sre.c:825)
==9396==    by 0x4F8333D: pattern_match (_sre.c:1959)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== Invalid read of size 4
==9396==    at 0x4ED16D3: PyObject_Free (obmalloc.c:1013)
==9396==    by 0x4EC940A: dict_dealloc (dictobject.c:1040)
==9396==    by 0x4E9566A: class_dealloc (classobject.c:195)
==9396==    by 0x4EE51EC: tupledealloc (tupleobject.c:222)
==9396==    by 0x4E9567A: class_dealloc (classobject.c:194)
==9396==    by 0x4E988CA: instance_dealloc (classobject.c:680)
==9396==    by 0x4EC72C6: insertdict_by_entry (dictobject.c:519)
==9396==    by 0x4ECA79B: insertdict (dictobject.c:556)
==9396==    by 0x4ECA79B: dict_set_item_by_hash_or_entry (dictobject.c:795)
==9396==    by 0x4ECA79B: PyDict_SetItem (dictobject.c:848)
==9396==    by 0x4ECDA8C: _PyModule_Clear (moduleobject.c:139)
==9396==    by 0x4F4B691: PyImport_Cleanup (import.c:530)
==9396==    by 0x4F5857A: Py_Finalize (pythonrun.c:458)
==9396==    by 0x4F6E8E4: Py_Main (main.c:670)
==9396==  Address 0x10551020 is 576 bytes inside a block of size 1,183 free'd
==9396==    at 0x0: ???
==9396==  Block was alloc'd at
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED9A79: PyString_FromStringAndSize (stringobject.c:88)
==9396==    by 0x4F502F9: r_object (marshal.c:814)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==9396== 
==9396== 
==9396== HEAP SUMMARY:
==9396==     in use at exit: 4,959,703 bytes in 7,143 blocks
==9396==   total heap usage: 59,465 allocs, 52,322 frees, 56,577,004 bytes allocated
==9396== 
==9396== 80 bytes in 1 blocks are possibly lost in loss record 744 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124C9ED5: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123E591F: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EDFD4: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C5FDA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 80 bytes in 1 blocks are possibly lost in loss record 745 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124C9ED5: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123E591F: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EEE35: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD682: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124ADA33: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123D8D77: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6040: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 787 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123E736A: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C5FCA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 788 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x125077BE: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12507B95: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123ED88F: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C5FDA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 789 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12509C35: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12507897: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12507B95: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123ED88F: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C5FDA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 790 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x125077BE: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12507BC9: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123ED88F: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C5FDA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 791 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12509C35: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12507897: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12507BC9: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123ED88F: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C5FDA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 792 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x12452DD2: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453467: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453951: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EE0B4: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C5FDA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 793 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6018: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 794 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD7FC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123D8D77: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6040: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 795 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD81C: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123D8D77: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6040: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 796 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD83C: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123D8D77: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6040: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 797 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x12452DD2: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453467: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453951: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EEE57: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD682: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124ADA33: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123D8D77: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6040: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 798 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x12452DD2: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453429: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453951: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EEE57: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD682: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124ADA33: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123D8D77: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6040: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 799 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x124537BC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12509C35: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12509E4A: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD580: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124ADA33: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123D8D77: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C6040: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 800 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x12452DD2: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453429: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453951: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EEE57: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AD682: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124ADA33: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123ABB02: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123AD8FE: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x122DF44B: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x1241995A: cuDevicePrimaryCtxRetain (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A964C8: do_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 801 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x12452DD2: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453429: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124539C4: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EE726: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124A3AAE: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AF9F5: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AFEC9: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x125188BD: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12519077: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x125197BD: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123ABB41: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 802 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x12452DD2: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453429: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453951: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123E83CC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123E68D4: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x1250BB2C: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x1250C1A8: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x1250C3CC: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124A2BEF: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124A351F: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AF9F5: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396== 
==9396== 136 bytes in 1 blocks are possibly lost in loss record 803 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x12452DD2: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12453429: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124539C4: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EF029: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x124AFF9B: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123A4FCA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123ABDBA: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123AD8FE: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x122DF44B: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x1241995A: cuDevicePrimaryCtxRetain (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A964C8: do_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396== 
==9396== 304 bytes in 1 blocks are possibly lost in loss record 871 of 1,437
==9396==    at 0x4C2FB45: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4013BAA: allocate_dtv (dl-tls.c:322)
==9396==    by 0x4013BAA: _dl_allocate_tls (dl-tls.c:539)
==9396==    by 0x523E29B: allocate_stack (allocatestack.c:586)
==9396==    by 0x523E29B: pthread_create@@GLIBC_2.2.5 (pthread_create.c:663)
==9396==    by 0x123F4F1E: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123EBFDD: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x123C60BE: ??? (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x12418ACC: cuInit (in /usr/lib/x86_64-linux-gnu/libcuda.so.384.66)
==9396==    by 0x6A8FF7A: setup_lib (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A96765: cuda_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x6A7ED32: gpucontext_init (in /home/notoraptor/.local/lib/libgpuarray.so.3.0)
==9396==    by 0x68504D1: __pyx_f_5pygpu_8gpuarray_pygpu_init (gpuarray.c:9104)
==9396==    by 0x6852298: __pyx_pf_5pygpu_8gpuarray_22init (gpuarray.c:9650)
==9396==    by 0x6852298: __pyx_pw_5pygpu_8gpuarray_23init (gpuarray.c:9298)
==9396== 
==9396== 520 bytes in 1 blocks are possibly lost in loss record 894 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EF3E6F: slot_tp_init (typeobject.c:5806)
==9396==    by 0x4EE7567: type_call (typeobject.c:765)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396== 
==9396== 520 bytes in 1 blocks are possibly lost in loss record 895 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E88A65: PyObject_CallFunctionObjArgs (abstract.c:2774)
==9396==    by 0xC33ABDB: ufunc_get_doc (ufunc_object.c:5623)
==9396==    by 0x4ECF37A: _PyObject_GenericGetAttrWithDict (object.c:1439)
==9396==    by 0x4F2C5D0: builtin_getattr (bltinmodule.c:848)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 528 bytes in 1 blocks are possibly lost in loss record 901 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EE785C: slot_tp_new (typeobject.c:5849)
==9396==    by 0x4EE7522: type_call (typeobject.c:749)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E88A65: PyObject_CallFunctionObjArgs (abstract.c:2774)
==9396==    by 0x4F321EB: build_class (ceval.c:4964)
==9396==    by 0x4F321EB: PyEval_EvalFrameEx (ceval.c:2160)
==9396== 
==9396== 536 bytes in 1 blocks are possibly lost in loss record 903 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396== 
==9396== 544 bytes in 1 blocks are possibly lost in loss record 904 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4EB3B67: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EE785C: slot_tp_new (typeobject.c:5849)
==9396==    by 0x4EE7522: type_call (typeobject.c:749)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F3680C: do_call (ceval.c:4569)
==9396==    by 0x4F3680C: call_function (ceval.c:4374)
==9396==    by 0x4F3680C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 560 bytes in 1 blocks are possibly lost in loss record 907 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EF42AB: slot_tp_call (typeobject.c:5546)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F3680C: do_call (ceval.c:4569)
==9396==    by 0x4F3680C: call_function (ceval.c:4374)
==9396==    by 0x4F3680C: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 560 bytes in 1 blocks are possibly lost in loss record 908 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EF3E6F: slot_tp_init (typeobject.c:5806)
==9396==    by 0x4EE7567: type_call (typeobject.c:765)
==9396== 
==9396== 560 bytes in 1 blocks are possibly lost in loss record 909 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED1D54: PyObject_Realloc (obmalloc.c:1272)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396== 
==9396== 584 bytes in 1 blocks are possibly lost in loss record 914 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396== 
==9396== 600 bytes in 1 blocks are possibly lost in loss record 918 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EE785C: slot_tp_new (typeobject.c:5849)
==9396==    by 0x4EE7522: type_call (typeobject.c:749)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4F3680C: do_call (ceval.c:4569)
==9396==    by 0x4F3680C: call_function (ceval.c:4374)
==9396==    by 0x4F3680C: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== 608 bytes in 1 blocks are possibly lost in loss record 919 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED1D54: PyObject_Realloc (obmalloc.c:1272)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EF3E6F: slot_tp_init (typeobject.c:5806)
==9396== 
==9396== 640 bytes in 1 blocks are possibly lost in loss record 923 of 1,437
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 728 bytes in 1 blocks are possibly lost in loss record 940 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED1D54: PyObject_Realloc (obmalloc.c:1272)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 728 bytes in 1 blocks are possibly lost in loss record 941 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED1D54: PyObject_Realloc (obmalloc.c:1272)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== 1,104 bytes in 2 blocks are possibly lost in loss record 1,218 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED1D54: PyObject_Realloc (obmalloc.c:1272)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38416: PyEval_EvalCodeEx (ceval.c:3365)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4E9664E: instancemethod_call (classobject.c:2602)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396==    by 0x4EF3E6F: slot_tp_init (typeobject.c:5806)
==9396==    by 0x4EE7567: type_call (typeobject.c:765)
==9396==    by 0x4E83E92: PyObject_Call (abstract.c:2547)
==9396== 
==9396== 1,280 bytes in 2 blocks are possibly lost in loss record 1,223 of 1,437
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== 1,584 bytes in 3 blocks are possibly lost in loss record 1,240 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4EB3A60: function_call (funcobject.c:523)
==9396== 
==9396== 1,920 bytes in 3 blocks are possibly lost in loss record 1,249 of 1,437
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 2,912 bytes in 4 blocks are possibly lost in loss record 1,262 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396== 
==9396== 3,200 bytes in 5 blocks are possibly lost in loss record 1,341 of 1,437
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== 3,640 bytes in 5 blocks are possibly lost in loss record 1,348 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EB3150: PyFrame_New (frameobject.c:680)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== 3,640 bytes in 5 blocks are possibly lost in loss record 1,349 of 1,437
==9396==    at 0x4C2FD4F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F6F4C8: _PyObject_GC_Resize (gcmodule.c:1544)
==9396==    by 0x4EB30FC: PyFrame_New (frameobject.c:693)
==9396==    by 0x4F38251: fast_function (ceval.c:4426)
==9396==    by 0x4F38251: call_function (ceval.c:4372)
==9396==    by 0x4F38251: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38344: fast_function (ceval.c:4437)
==9396==    by 0x4F38344: call_function (ceval.c:4372)
==9396==    by 0x4F38344: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396== 
==9396== 5,464 bytes in 2 blocks are possibly lost in loss record 1,363 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EE541E: PyTuple_New (tupleobject.c:90)
==9396==    by 0x4F50A3D: r_object (marshal.c:885)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396== 
==9396== 5,688 bytes in 2 blocks are possibly lost in loss record 1,368 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EE541E: PyTuple_New (tupleobject.c:90)
==9396==    by 0x4EE5619: tupleconcat (tupleobject.c:452)
==9396==    by 0x4F30F61: PyEval_EvalFrameEx (ceval.c:1484)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E343: load_next (import.c:2539)
==9396== 
==9396== 57,584 bytes in 35 blocks are possibly lost in loss record 1,418 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4F707B8: _PyObject_GC_Malloc (gcmodule.c:1499)
==9396==    by 0x4F708FD: _PyObject_GC_NewVar (gcmodule.c:1531)
==9396==    by 0x4EE541E: PyTuple_New (tupleobject.c:90)
==9396==    by 0x4F50A3D: r_object (marshal.c:885)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F50A81: r_object (marshal.c:891)
==9396==    by 0x4F50BEB: r_object (marshal.c:1024)
==9396==    by 0x4F51717: PyMarshal_ReadObjectFromString (marshal.c:1188)
==9396==    by 0x4F5183E: PyMarshal_ReadLastObjectFromFile (marshal.c:1149)
==9396==    by 0x4F4D2B5: read_compiled_module (import.c:823)
==9396==    by 0x4F4D2B5: load_source_module (import.c:1094)
==9396== 
==9396== 154,502 bytes in 82 blocks are possibly lost in loss record 1,432 of 1,437
==9396==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9396==    by 0x4ED9A79: PyString_FromStringAndSize (stringobject.c:88)
==9396==    by 0x4F371E4: call_function (ceval.c:4352)
==9396==    by 0x4F371E4: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F381F6: fast_function (ceval.c:4447)
==9396==    by 0x4F381F6: call_function (ceval.c:4372)
==9396==    by 0x4F381F6: PyEval_EvalFrameEx (ceval.c:2989)
==9396==    by 0x4F38C3D: PyEval_EvalCodeEx (ceval.c:3584)
==9396==    by 0x4F38D51: PyEval_EvalCode (ceval.c:669)
==9396==    by 0x4F4ABD1: PyImport_ExecCodeModuleEx (import.c:731)
==9396==    by 0x4F4D31D: load_source_module (import.c:1121)
==9396==    by 0x4F4E0D0: import_submodule (import.c:2725)
==9396==    by 0x4F4E60B: ensure_fromlist (import.c:2631)
==9396==    by 0x4F4EAF3: import_module_level (import.c:2293)
==9396==    by 0x4F4EAF3: PyImport_ImportModuleLevel (import.c:2312)
==9396== 
==9396== LEAK SUMMARY:
==9396==    definitely lost: 0 bytes in 0 blocks
==9396==    indirectly lost: 0 bytes in 0 blocks
==9396==      possibly lost: 253,510 bytes in 184 blocks
==9396==    still reachable: 4,706,193 bytes in 6,959 blocks
==9396==         suppressed: 0 bytes in 0 blocks
==9396== Reachable blocks (those to which a pointer was found) are not shown.
==9396== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==9396== 
==9396== For counts of detected and suppressed errors, rerun with: -v
==9396== ERROR SUMMARY: 516 errors from 93 contexts (suppressed: 1878 from 64)
